export const LOGIN__ERROR: string = "Account does not exist.";
export const LOGIN__SUCCESS: string = "Login successfully.";
export const LOGOUT__SUCCESS: string = "Logout successfully.";
export const REGIS__ERROR: string = "Account already exists.";
export const REGIS__SUCCESS: string = "Sign up successfully.";
export const PAYMENT__SUCCESS: string = "Payment successfully";
export const ADDTOCART__SUCCESS: string = "Add to cart successfully";
export const LIKED__SUCCESS: string = "Liked successfully";
export const UNLIKE__SUCCESS: string = "Unlike successfully";
